### ISSUE TITLE
Export the model to TFlite

### ISSUE THREAD

**Issue by fbertola** [apacha/MusicObjectDetector-TF#4]
Hi!
I want to export the latest model to TFlite but it is currently not possible with the frozen graph provided (https://github.com/tensorflow/tensorflow/issues/28485). One solution should be using the export scripts inside the `object_detection` folder, but the checkpoints are necessary.
Could you help me?

**Comment by apacha** [comment]
Hi,
that is an excellent question. I've never considered TFLite yet, but of course it would be useful to provide the trained models in that format. However, I currently don't have access to the machine where the checkpoints are stored. I will continue my work here in the next few weeks, but if you need it before that, I would recommend that you retrain the model on the muscima++ dataset yourself. 

I would like to resume my work that I started in #3. The idea was to have two networks: one that detects staves and one that actually performs object detection. From some preliminary experiments, this showed exceptional results, however, I haven't been able to release a fully running version of this yet. I hope that I can resume my research soon.

If I can help you in any other way, just let me know.

**Comment by fbertola** [comment]
Hi,
thanks for the response and for the amazing work done! I ended up retraining the model myself using the SSD configuration. I successfully exported the TFlite model but there are serious issues. Performances are quite bad, but that's not a real problem for me. The problem is that the accuracy is extremely low, not comparable to the Faster RCNN model.
I haven't done any other test yet, as it took quite long to train the model with 80k steps 😅 .

Anyway, if you need it, I can share the checkpoint and the exported model.

Thanks again.

**Comment by apacha** [comment]
That's right. SSD detectors are much worse due to the nature of music object detection, where you have to detect many tiny objects in a high-resolution images, as opposed to having a few big objects in a low-resolution image (for which most object detectors were developed).

Yes, it would be great to share the trained models. And what would be even more would be a short description, a simple script or a notebook on how to obtain the TFLite model from a checkpoint (at least I haven't done this before, so I'm curious).

**Comment by phamconganh** [comment]
@fbertola can you share the checkpoint and the exported model?
